# 异步编程
主流的JS环境主要采用单线程原因：  
> 最初是浏览器端脚本语言，为了实现页面动态交互，页面交互核心是dom操作，必须使用单线程，否则会出现复杂的线程同步问题

为了解决耗时问题，将执行模式分成两种
- 同步模式 synchronous  
  - 依次执行
  - 如果其中某一行代码执行时间过长，就会使后续代码被延迟（阻塞）
- 异步模式 asynchronous（处理大量耗时任务）  
  - 不会等待任务结束才开始下一个任务，开启后立即往后执行下一个任务  
  - 后续逻辑一般通过回调函数的方式定义，耗时任务完成过后自动执行回调函数

异步调用实现过程&原理
- 加载整体代码，在调用栈中压入一个匿名全局调用Anonymous
- 依次执行每行代码，压栈，执行，打印，弹栈
- 异步任务放到Web APIs中（异步线程单独执行异步任务，在执行完成后，将这个任务的回调放入到消息队列中）
- 整体匿名调用完成，清空调用栈
- js主线程完成所有任务后会依次执行消息队列中的任务
- 当调用栈所有任务结束 / 消息队列发生变化时，事件循环把消息队列中的第一个取出，压入调用栈并执行

## 回调函数（所有异步编程方案的根基）
函数A作为参数(函数引用)传递到另一个函数B中，并且这个函数B执行函数A。我们就说函数A叫做回调函数
```
const foo = callback => setTimeout(() => callback(), 3000)
foo(() => {
  console.log('这就是一个回调函数')
  console.log('调用者定义这个函数，执行者执行者个函数')
  console.log('调用者告诉执行者异步任务结束后应该做什么')
})
```
---

## Promise(更优的异步编程统一方案)
- pending -> fulfilled / rejected
- 一旦状态改变，就不会再变
```
const promise = new Promise((resolve, reject) => {
  // fulfilled
  // resolve(100)
  // rejected
  reject(new Error('promise rejected'))
})
promise.then(
  res => { // onFulfilled },
  err => { // onRejected }
)
```

## Promise 链式调用（避免回调嵌套）
- Promise对象的then方法回返回一个全新的promise对象
- 后面的then方法就是上一个then返回的promise注册回调
- 前面then方法中回调函数的返回值会作为后面then方法回调的参数
- 如果回调中返回的是promise对象，那后面then方法的回调会等待它的结束
```
promise
  .then(res => {
    console.log('111')
    return '333'
  })
  .then(res => console.log('222', res)) => 222 333
  .then(res => console.log('333'))
  .then(res => console.log('444'))
```

## Promise 异常处理
- catch 等价于 then(undefined, err => onRejected(err))
- 链式调用error会向后传递直至被捕获
- then中的onRejected只能捕获最初promise的error
```
promise.then(console.log, err => console.log(err))
promise
  .then(value => {
    console.log(value)
    return ajax('/err-url')
  }).catch(console.log)
```

## Promise 静态方法
Promise.resolve
- 接收一个值，转换成promise对象
- 接收promise对象，会原样返回
- 有then方法的对象（可接收到onFulfilled/onRejected）也可作为promise对象执行

Promise.reject
- 创建一个失败的promise对象
```
Promise.resolve(foo).then(console.log)
=> foo
Promise.reject(new Error('rejected')).catch(console.log)
=> Error: rejected
```

## Promise 并行执行
Promise.all
- 将多个promise合并成一个新的promise，内部所有promise完成后，新的promise才会完成
- 结果是个数组，包含每个异步任务执行结果
- 任一个内部promise失败，新的promise也会失败
```
ajax('/api/urls.json').then(value => {
  const urls = Object.values(value)
  const tasks = urls.map(url => ajax(url))
  return Promise.all(tasks)
}).then(console.log)
```
Promise.race
- 只会等待第一个结束的任务
```
Promise.race([request, timeout]).then(console.log).catch(console.log)
```

## Promise 执行时序 / 宏任务 vs. 微任务
宏任务
- 回调队列中的任务
- 宏任务执行过程中可以临时加上一些额外的需求，可以选择作为一个新的宏任务进到队列中排队，也可以作为当前任务的微任务
- 大部分异步调用都是作为宏任务执行(如setTimeout)

微任务（提高整体相应能力）
- 当前任务结束过后立即执行
- promise的回调作为微任务执行，直接在本轮任务结束立即执行
- promise & mutationObserver & process.nextTick 作为微任务

```
console.log('global start')
setTimeout(() => console.log('setTimeout'), 0)
Promise.resolve()
  .then(() => console.log('promise'))
  .then(() => console.log('promise2'))
  .then(() => console.log('promise3'))
console.log('global end')
=> start -> end -> promise1...3 => setTimeout
```
---

## generator异步方案（ES2015）
- 调用生成器函数会生成生成器对象
- 手动调用next，才会开始执行
- next方法拿到返回的值，拿到的值内部有done属性（是否执行完毕）
- yield 会向外返回一个值，暂停生成器的执行，直到下一个next
- next方法若传入了参数，会作为yeild的返回值
- throw方法会在生成器内部抛出异常，可以通过try/catch捕获异常
```
function * foo () {
  // yield 'foo'
  try {
    const res = yield 'foo'
    console.log(res)
  } catch(e) {
    console.log(e)
  }
}
const generator = foo()
// generator.next('bar')
// generator.throw(new Error('generator error'))
const result = generator.next()
console.log(result) => {value: "foo", done: false}
```
---

## Async / Await (ES2017)
- async返回promise对象
- await只能出现在async内部
```
const main = async () => {
  try {
    const users = await ajax('/api/users.json')
    console.log(users)
    const posts = await ajax('/api/posts.json')
    console.log(posts)
  } catch(e) {
    console.log(e)
  }
}
const promise = main()
promise.then(() => console.log('all completed'))
=> 依次打印出 users 和 posts 并在最后打印 all completed
```